const projectInfoArray = [
  {
    id: "p-1",
    title: "E-Commerce Restaurant app",
    tech: "SpringBoot, thymeleaf, HTML/CSS/JS, Spring Security, MySQL, Razorpay,Font-awsome,PrintJs,ChartJS",
    category: "Web app",
    desc: "A web app for managing restaurants,cafe or any sort or e-commerce business, allows users to view available producsts by browsing through the category and make a purchase, admin can manage the employees/users/products , can view the dashboard etc",
    coverImage: "/path",
    site: "/ec-res",
    github: "https://github.com/Vishal-Bala907/Cafe-webb-App",
    image: "../../myporjects/ProjectImages/res.jpg",
  },
  {
    id: "p-3",
    title: "Wheather app",
    tech: "React JS, Bootstrap and visual crossing",
    category: "web app",
    desc: "Wheather app built on react js allows you to get the information about wheather conditions, you can see the wheather deatiails of today , hourly , next three/seven/fifteen days",
    coverImage: "/path",
    site: "https://vishal-bala907.github.io/Wether-App/",
    github: "https://github.com/Vishal-Bala907/Wether-App",
    image: "../../myporjects/ProjectImages/whe.jpg",
  },
  {
    id: "p-8",
    title: "Daily progress",
    tech: "React JS, tailwind and Spring Boot",
    category: "web app",
    desc: "A comprehensive and light weight application, which lets you to note your daily routine and show your progress in a pie chart",
    coverImage: "/daily-prog",
    site: "/daily-prog",
    github:
      "https://github.com/Vishal-Bala907/Frontends-in-react/tree/main/DailyProgressTracker",
    image: "../../myporjects/ProjectImages/whe.jpg",
  },

  {
    id: "p-2",
    title: "Cafe management system advance",
    tech: "JavaFX, Hibernate, MySQL/H2",
    category: "Desktop app",
    desc: "desktop app built in JavaFX framework, this app will provides you all the functionality which was provides in the lite versoin plus some more advance featues like Dashboard, graphs and different views to different users according to their role",
    coverImage: "/path",
    site: "/cafe-adv",
    github: "https://github.com/Vishal-Bala907/Cafe-management-Sytem-Advance",
    image: "../../myporjects/ProjectImages/cafe2.jpg",
  },

  {
    id: "p-4",
    title: "Temple trust donation",
    tech: "SpringBoot, thymeleaf, HTML/CSS/JS , Bootstrap, Spring Security, MySQL, Razorpay",
    category: "web app",
    desc: "A web app for managing temples, allows users to donate , purchase some pooja/related stuffs , idols of god or prasaad , make booking for the temple hall for functions , book their aarti/pooja slots or can even book an artist for bhajan and kirtan",
    coverImage: "/path",
    site: "/temple",
    github: "https://github.com/Vishal-Bala907/Temple-trust-updated",
    image: "../../myporjects/ProjectImages/temple.jpg",
  },

  {
    id: "p-5",
    title: "Clock Stopwatch and timer",
    tech: "JavaFX",
    category: "Desktop app",
    desc: "A simple and usefull clock desktop app built in JavaFX framework, this app will also provide a basic timer and stopwatch",
    coverImage: "/path",
    site: "/clock",
    github: "https://github.com/Vishal-Bala907/Clock-App",
    image: "../../myporjects/ProjectImages/clock.jpg",
  },
  {
    id: "p-6",
    title: "Cafe management system lite",
    tech: "JavaFX, Hibernate, MySQL/H2",
    category: "Desktop app",
    desc: "A simple and usefull cafe management desktop app built in JavaFX framework, this app will only provides you with some functionalities like mananeging employee and products etc ",
    coverImage: "/path",
    site: "/cafe-lite",
    github: "https://github.com/Vishal-Bala907/Cafe-management-Sytem-lite",
    image: "../../myporjects/ProjectImages/cafe1.jpg",
  },

  {
    id: "p-7",
    title: "Portfolio on react",
    tech: "React JS,Bootsrap,typed.js , AOS",
    category: "web app",
    desc: "Hi, I'm Vishal Bala, a dedicated software developer based in Kota, Rajasthan. With a Bachelor's degree in Computer Applications from Maa Bharti PG College, Kota, I have developed a robust foundation in software development. My passion lies in creating efficient and innovative solutions to complex problems.",
    coverImage: "/path",
    site: "/",
    github: "https://github.com/Vishal-Bala907/Portfolio-site",
    image: "../../myporjects/ProjectImages/react.jpg",
  },
];

export default projectInfoArray;
