const projectInfoArray = [
  {
    id: "p-1",
    title: "E-Commerce Restaurant app",
    tech: "SpringBoot, thymeleaf, HTML/CSS/JS, Spring Security, MySQL, Razorpay,Font-awsome,PrintJs,ChartJS",
    category: "Desktop app",
    desc: "A webb app for managing restaurants,cafe or any sort or e-commerce business, allows users to view available producsts by browsing through the category and make a purchase, admin can manage the employees/users/products , can view the dashboard etc",
    coverImage: "/path",
    site: "#",
    github: "https://github.com/Vishal-Bala907/Cafe-management-Sytem-lite",
    image: "../../porjects/images/res.jpg",
  },

  {
    id: "p-2",
    title: "Cage management system advance",
    tech: "JavaFX, Hibernate, MySQL/H2",
    category: "Desktop app",
    desc: "desktop app built in JavaFX framework, this app will provides you all the functionality which was provides in the lite versoin plus some more advance featues like Dashboard, graphs and different views to different users according to their role",
    coverImage: "/path",
    site: "#",
    github: "https://github.com/Vishal-Bala907/Cafe-management-Sytem-lite",
    image: "../../porjects/images/cafe2.jpg",
  },
  {
    id: "p-3",
    title: "Wheather app",
    tech: "React JS, Bootstrap and visual crossing",
    category: "webb app",
    desc: "Wheather app built on react js allows you to get the information about wheather conditions, you can see the wheather deatiails of today , hourly , next three/seven/fifteen days",
    coverImage: "/path",
    site: "#",
    github: "https://github.com/Vishal-Bala907/Cafe-management-Sytem-lite",
    image: "../../porjects/images/whe.jpg",
  },
  {
    id: "p-4",
    title: "Temple trust donation",
    tech: "SpringBoot, thymeleaf, HTML/CSS/JS , Bootstrap, Spring Security, MySQL, Razorpay",
    category: "Webb app",
    desc: "A webb app for managing temples, allows users to donate , purchase some pooja/related stuffs , idols of god or prasaad , make booking for the temple hall for functions , book their aarti/pooja slots or can even book an artist for bhajan and kirtan",
    coverImage: "/path",
    site: "/clock",
    github: "https://github.com/Vishal-Bala907/Cafe-management-Sytem-lite",
    image: "../../porjects/images/temple.jpg",
  },

  {
    id: "p-5",
    title: "Clock Stopwatch and timer",
    tech: "JavaFX",
    category: "Desktop app",
    desc: "A simple and usefull clock desktop app built in JavaFX framework, this app will also provide a basic timer and stopwatch",
    coverImage: "/path",
    site: "/clock",
    github: "https://github.com/Vishal-Bala907/Cafe-management-Sytem-lite",
    image: "../../porjects/images/clock.jpg",
  },
  {
    id: "p-6",
    title: "Cafe management system lite",
    tech: "JavaFX, Hibernate, MySQL/H2",
    category: "Desktop app",
    desc: "A simple and usefull cafe management desktop app built in JavaFX framework, this app will only provides you with some functionalities like mananeging employee and products etc ",
    coverImage: "/path",
    site: "#",
    github: "https://github.com/Vishal-Bala907/Cafe-management-Sytem-lite",
    image: "../../porjects/images/cafe1.jpg",
  },

  {
    id: "p-7",
    title: "Small projects on react",
    tech: "React JS",
    category: "Webb apps",
    desc: "Calculator, Todo App, Myntra clone, Microsoft teams clone",
    coverImage: "/path",
    site: "#",
    github: "https://github.com/Vishal-Bala907/Cafe-management-Sytem-lite",
    image: "../../porjects/images/react.jpg",
  },
];

export default projectInfoArray;
